module.exports = {
  someSidebar1: {
    Introduction: ["intro", "aboutdocs"],
    "Download and Setup": [
      "installation",
      {
        type: "link",
        label: "Windows Desktop App",
        href: "/installation#installation-on-windows",
      },
      {
        type: "link",
        label: "macOS Desktop App",
        href: "/installation#installation-on-macos",
      },
      {
        type: "link",
        label: "Linux Desktop App",
        href: "/installation#installation-on-linux",
      },
      {
        type: "link",
        label: "Android App",
        href: "/installation#installation-on-android",
      },
      {
        type: "link",
        label: "Firefox Extension",
        href: "/installation#installing-the-firefox-browser-extension",
      },
      {
        type: "link",
        label: "Chrome Extension",
        href: "/installation#installing-the-chrome-browser-extension",
      },
      {
        type: "link",
        label: "Portable mode",
        href: "/installation#running-in-portable-mode",
      },
      "tutorials/setup-tagspaces-pro-web",
      {
        type: "link",
        label: "Setup Command Line Tool",
        href: "/installation#tagspaces-command-line-tool",
      },
    ],
    "Get Started": [
      "ui/userinterface",
      {
        type: "link",
        label: "File browsing area",
        href: "/ui/userinterface/#browsing-area",
      },
      {
        type: "link",
        label: "File preview area",
        href: "/ui/userinterface/#preview-area",
      },
      {
        type: "link",
        label: "File properties",
        href: "/ui/userinterface/#file-properties-area",
      },
      {
        type: "link",
        label: "Folder properties",
        href: "/ui/userinterface/#folder-properties-area",
      },
      {
        type: "link",
        label: "Other features",
        href: "/ui/userinterface/#dark-mode",
      },
      // "ui/userinterface/#dark-mode",
      // "ui/userinterface/#zoomable-user-interface",
      // "ui/userinterface/#full-screen-mode",
      "ui/keybindings",
      "ui/i18n",
    ],
    Locations: [
      "ui/locations",
      {
        type: "link",
        label: "Local Locations",
        href: "/ui/locations/#local-locations",
      },
      {
        type: "link",
        label: "Object Storage Locations (S3)",
        href: "/ui/locations/#object-storage-locations",
      },
      {
        type: "link",
        label: "Advanced Features",
        href: "/ui/locations/#advanced-features",
      },
    ],
    "Tag Files and Folders": [
      "tagging",
      {
        type: "link",
        label: "File tagging using filename",
        href: "/tagging/#file-tagging-based-on-filenames",
      },
      {
        type: "link",
        label: "File tagging using sidecar file",
        href: "/tagging/#file-tagging-with-sidecar-file",
      },
      {
        type: "link",
        label: "Folder tagging",
        href: "/tagging/#folder-tagging-with-sidecar-file",
      },
      {
        type: "link",
        label: "Tagging operation on many entries",
        href: "/tagging/#tag-operations-on-many-entries",
      },
      {
        type: "link",
        label: "Tagging with drag and drop",
        href: "/tagging/#tagging-with-drag-and-drop",
      },
      "ui/taglibrary",
      {
        type: "link",
        label: "Smart tags",
        href: "/ui/taglibrary/#smart-tags",
      },
      {
        type: "link",
        label: "Tagging with timestamps",
        href: "/ui/taglibrary/#custom-timestamp-tagging",
      },
      {
        type: "link",
        label: "Geo-tagging",
        href: "/ui/taglibrary/#geo-tagging",
      },
      {
        type: "link",
        label: "Location tags",
        href: "/ui/taglibrary/#location-tags",
      },
    ],
    "Search and Find": [
      "search",
      {
        type: "link",
        label: "Basic Search",
        href: "/search/#basic-search",
      },
      {
        type: "link",
        label: "Advanced Search",
        href: "/search/#advanced-search",
      },
      {
        type: "link",
        label: "Full-Text Search",
        href: "/search/#full-text-search",
      },
      {
        type: "link",
        label: "Global Search",
        href: "/search/#global-search",
      },
      {
        type: "link",
        label: "Stored Search Queries",
        href: "/search/#stored-search-queries",
      },
    ],
    "Browse Files in Perspectives": [
      "browsing-files",
      "perspectives/grid",
      "perspectives/gallery",
      "perspectives/mapique",
      "perspectives/kanban",
      "perspectives/folderviz",
    ],
    "Preview and Print Files": [
      "viewing-files",
      {
        type: "link",
        label: "Supported File Formats",
        href: "/viewing-files/#supported-file-formats",
      },
      {
        type: "link",
        label: "Print files",
        href: "/viewing-files/#printing-files",
      },
      "extensions/media-player",
      "extensions/epub-viewer",
      "extensions/html-viewer",
      "extensions/image-viewer",
      "extensions/md-viewer",
      "extensions/mhtml-viewer",
      "extensions/pdf-viewer",
      "extensions/rtf-viewer",
      "extensions/document-viewer",
      "extensions/spreadsheet-viewer",
      "extensions/text-viewer",
      "extensions/url-viewer",
      "extensions/archive-viewer",
    ],
    "Create, Edit and Share Files": [
      "creating-files",
      {
        type: "link",
        label: "Import Files",
        href: "/creating-files/#importing-files",
      },
      "editing-files",
      "extensions/md-editor",
      "extensions/html-editor",
      "extensions/text-editor",
      "extensions/json-editor",
    ],
    "Share and Link Files": ["sharing", "linking"],
    Settings: [
      "ui/settings",
      {
        type: "link",
        label: "General",
        href: "/ui/settings/#general",
      },
      {
        type: "link",
        label: "File Types",
        href: "/ui/settings/#file-types",
      },
      {
        type: "link",
        label: "Key Bindings",
        href: "/ui/settings/#key-bindings",
      },
      {
        type: "link",
        label: "Advanced",
        href: "/ui/settings/#advanced",
      },
    ],
    "Advanced Functionalities": [
      "annotations",
      {
        type: "link",
        label: "Custom Folder Color",
        href: "/annotations/#custom-folder-color",
      },
      "thumbnails",
      {
        type: "link",
        label: "Custom Thumbnail",
        href: "/thumbnails/#custom-thumbnail",
      },
      "dev/metafileformats",
      "dev/external-config",
    ],
    Tutorials: [
      "web-clipper",
      "tutorials/file-syncing",
      "tutorials/sharing-tags",
      "tutorials/s3-bucket-locations",
      "tutorials/setup-minio-bucket-nas",
      "dev/extension-development-guide",
      "selfhosting",
      "tutorials/sabre-dav-setup",
    ],
  },
};
