wget https://raw.githubusercontent.com/tagspaces/viewerAudioVideo/master/README.md -O external/viewerAudioVideo.md
wget https://raw.githubusercontent.com/tagspaces/viewerEPUB/master/README.md -O external/viewerEPUB.md
wget https://raw.githubusercontent.com/tagspaces/viewerHTML/master/README.md -O external/viewerHTML.md
wget https://raw.githubusercontent.com/tagspaces/viewerImage/master/README.md -O external/viewerImage.md
wget https://raw.githubusercontent.com/tagspaces/viewerURL/master/README.md -O external/viewerURL.md
wget https://raw.githubusercontent.com/tagspaces/viewerMD/master/README.md -O external/viewerMD.md
wget https://raw.githubusercontent.com/tagspaces/viewerMHTML/master/README.md -O external/viewerMHTML.md
wget https://raw.githubusercontent.com/tagspaces/editorODF/master/README.md -O external/editorODF.md
wget https://raw.githubusercontent.com/tagspaces/viewerPDF/master/README.md -O external/viewerPDF.md
wget https://raw.githubusercontent.com/tagspaces/viewerText/master/README.md -O external/viewerText.md
wget https://raw.githubusercontent.com/tagspaces/viewerBrowser/master/README.md -O external/viewerBrowser.md
wget https://raw.githubusercontent.com/tagspaces/viewerZIP/master/README.md -O external/viewerZIP.md
wget https://raw.githubusercontent.com/tagspaces/editorHTML/master/README.md -O external/editorHTML.md
wget https://raw.githubusercontent.com/tagspaces/editorJSON/master/README.md -O external/editorJSON.md
wget https://raw.githubusercontent.com/tagspaces/editorText/master/README.md -O external/editorText.md
wget https://raw.githubusercontent.com/tagspaces/perspectiveGrid/master/README.md -O external/perspectiveGrid.md
wget https://raw.githubusercontent.com/tagspaces/perspectiveList/master/README.md -O external/perspectiveList.md
wget https://raw.githubusercontent.com/tagspaces/perspectiveImageSwiper/master/README.md -O external/perspectiveImageSwiper.md
wget https://raw.githubusercontent.com/tagspaces/perspectiveGraph/master/README.md -O external/perspectiveGraph.md